name: Build Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    #- name: Build Docker image
    #  run: docker build -t test-image:latest .
      
    #- name: Run Docker container
    #  run: docker run -d --name test-container test-image:latest

    #- name: Stop Docker container
    #  run: docker stop test-container

    #- name: Remove Docker container
    #  run: docker rm test-container
      
    #- name: Test Docker image
    #  run: docker run --rm test-image:latest
