name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t your-image-name:latest .

    - name: Run Docker container
      run: docker run -d --name test-container your-image-name:latest

    - name: Test Docker container
      run: docker exec test-container your-test-command

    - name: Stop Docker container
      run: docker stop test-container

    - name: Remove Docker container
      run: docker rm test-container
